import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'campaignManagement',
        path: '',
        title: 'Kelola Campaign',
        translateKey: 'nav.campaignManagement',
        icon: 'campaign',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'campaigns',
                path: '/dashboard/campaigns',
                title: 'Daftar Campaign',
                translateKey: 'nav.campaigns',
                icon: 'campaignList',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'campaignCreate',
                path: '/dashboard/campaigns/create',
                title: 'Buat Campaign',
                translateKey: 'nav.campaignCreate',
                icon: 'campaignCreate',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'donasi',
                path: '/dashboard/donasi',
                title: 'Data Donasi',
                translateKey: 'nav.donasi',
                icon: 'donasi',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'contentManagement',
        path: '',
        title: 'Kelola Konten',
        translateKey: 'nav.contentManagement',
        icon: 'content',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'berita',
                path: '/dashboard/berita',
                title: 'Daftar Berita',
                translateKey: 'nav.berita',
                icon: 'berita',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'beritaCreate',
                path: '/dashboard/berita/create',
                title: 'Tulis Berita',
                translateKey: 'nav.beritaCreate',
                icon: 'beritaCreate',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'adminManagement',
        path: '',
        title: 'Administrasi',
        translateKey: 'nav.adminManagement',
        icon: 'admin',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'users',
                path: '/dashboard/users',
                title: 'Manajemen User',
                translateKey: 'nav.users',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'kontak',
                path: '/dashboard/kontak',
                title: 'Pesan Masuk',
                translateKey: 'nav.kontak',
                icon: 'kontak',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'settings',
                path: '/dashboard/settings',
                title: 'Pengaturan',
                translateKey: 'nav.settings',
                icon: 'settings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
